### ISSUE TITLE
NavBar

### ISSUE THREAD

**Issue by DrakeMorrison** [nss-evening-cohort-7/chatty-turophobia#13]
# Story
As a User I want a way to input my own message and submit

# Acceptance Criteria
**When** I want to use the application
**Then** I can do the above

# Technical Notes
- Use Bootstrap
- make navbar element fixed to top of page even when scrolling
- make id for input element = 'input'
- logo or title on left side, then the input field and clear messages button on right
- include a div for users to the left of the input field

**Comment by michaelclark2** [comment]
This is good, but I would put Clear Messages as its own issue and turn this Navbar issue into just making sure it is set up on the page
