### ISSUE TITLE
PrintToDom and domString

### ISSUE THREAD

**Issue by RitaSyed** [nss-evening-cohort-7/chatty-turophobia#14]
# Story 
As a user, when page first loaded, the user should see 5 messages below the input field. Each message has delete and edit button displayed next to it. Also there should be radio buttons with users names.

# Acceptance Criteria
**When** When dom.js opened
**Then** printToDom and domString functions should be there to print messages and radio buttons
**Then**  use for loops in the domString to limit messages to < 20;

# Technical Notes
- Delete and Edit buttons
- PrintToDom (domstring, id)
- printMessages (messageArray, usersArray)
- printUsers(usersArray)
- domString for loop i<20
- radio buttons with users name

**Comment by michaelclark2** [comment]
I think this could be split into two tickets.  One for the users, the other for the messages

**Comment by RitaSyed** [comment]
I think I will do one domstring instead of two. 

Best regards,
Margarita Patrick
