### ISSUE TITLE
Print messages to DOM by changing current function

### ISSUE THREAD

**Issue by RitaSyed** [nss-evening-cohort-7/chatty-turophobia#19]
# Story 
As a user, when user enters a new message in the input field and clicks submit button or return key pressed, new message appears below the first 5 messages in the message area with the user name and a time stamp.  

# Acceptance Criteria
**When** something typed in the input field and clicked submit button or return key pressed
 **And** new message should appear below with user name in bold text and time stamp 

# Technical Notes
-  events.json
 - printToDom function
- add message id to element

**Comment by DrakeMorrison** [comment]
Remember to add the edit and delete buttons as well. Could we give a class of 'delete-btn' to the delete buttons? thanks
