### ISSUE TITLE
Convert Emojis

### ISSUE THREAD

**Issue by michaelclark2** [nss-evening-cohort-7/chatty-turophobia#28]
# Story
As a user, I want to be able to use emojis in the chat input by using this syntax `:smile:` , etc.  
# Acceptance Criteria
**When** a word in the input field is found between `:`
**Then** it is converted into an emoji on the output of the message
# Technical Notes
- In emoji.js, include an object to convert the words into unicode characters
  - ```
    const emojis = {
      smile: "u+1something",
      frown: "u+1another",
    }
- the function should take an input string and replace certain phrases with emojis

**Comment by DrakeMorrison** [comment]
if the emoji is not valid: do what?
