### ISSUE TITLE
Edit Button (Edit message data)

### ISSUE THREAD

**Issue by michaelclark2** [nss-evening-cohort-7/chatty-turophobia#30]
# Story
As a user, when I submit an edited message, then it should print to the screen with the other messages
# Acceptance Criteria 
**When** a message is done being edited in the input box by pressing enter
**Then** the message should be updated in the data 
**And** the messages data should be reprinted to the page
# Technical Notes 
- when message is found by id when edit button is clicked, change found msg.message key to input value

**Comment by DrakeMorrison** [comment]
Callan: There should be an initial timestamp, and an updated (current) time
