### ISSUE TITLE
Button for Clear Messages

### ISSUE THREAD

**Issue by DrakeMorrison** [nss-evening-cohort-7/chatty-turophobia#33]
# Story
As a user, I want to be able to clear all the messages on the page

# Acceptance Criteria
**When** The user presses the "Clear Messages' button
**Then** the messages should no longer be on the page

# Technical Notes
- Add button to Nav after input field in index.html
- add event listener in events.js
- Use data Setter method to clear the message array
- when clicked, pass an empty array to printMessages (or function that prints the messages to the dom.)

**Comment by RitaSyed** [comment]
Closes #53

**Comment by RitaSyed** [comment]
Closes #53
